
export const VERKKIS_3060_AND_TI = 'https://www.verkkokauppa.com/fi/catalog/12149c/NVIDIA-GeForce-RTX-3060?sort=price%3Aasc&filter=ItemAdditionalInformationGraphicsProcessor%3AGeForce+RTX+3060&filter=AvailableImmediatelyAllChannels%3Aimmediately_shippable&filter=AvailableImmediatelyAllChannels%3Ajs&filter=ItemAdditionalInformationGraphicsProcessor%3AGeForce+RTX+3060+Ti'
export const VERKKIS_3070_AND_TI = 'https://www.verkkokauppa.com/fi/catalog/12070c/NVIDIA-GeForce-RTX-3070?filter=AvailableImmediatelyAllChannels%3Aimmediately_shippable'
export const PROSHOP_3060_3070_TI = 'https://www.proshop.fi/Naeytoenohjaimet?f~grafikkort_videoudganggrafikprocessorleverandor=nvidia-geforce-rtx-3060~nvidia-geforce-rtx-3060-ti~nvidia-geforce-rtx-3070~nvidia-geforce-rtx-3070-ti&pre=0&inv=1'
export const DATATRONIC_3060 = 'https://datatronic.fi/naytonohjaimet/s-2/grafiikkaprosessori-geforce_rtx_3060_ti+geforce_rtx_3060/l%C3%A4hetett%C3%A4viss%C3%A4_heti_myym%C3%A4l%C3%A4ss%C3%A4-kylla'
export const DATATRONIC_3060_TI = 'https://datatronic.fi/naytonohjaimet/s-2/grafiikkaprosessori-geforce_rtx_3060_ti/l%C3%A4hetett%C3%A4viss%C3%A4_heti_myym%C3%A4l%C3%A4ss%C3%A4-kylla'
export const DATATRONIC_3070 = 'https://datatronic.fi/naytonohjaimet/s-2/grafiikkaprosessori-geforce_rtx_3070/l%C3%A4hetett%C3%A4viss%C3%A4_heti_myym%C3%A4l%C3%A4ss%C3%A4-kylla'
export const DATATRONIC_3070_TI = 'https://datatronic.fi/naytonohjaimet/s-2/grafiikkaprosessori-geforce_rtx_3070_ti/l%C3%A4hetett%C3%A4viss%C3%A4_heti_myym%C3%A4l%C3%A4ss%C3%A4-kylla'
export const JIMMS_3060 = 'https://www.jimms.fi/fi/Product/List/000-1TL/komponentit--naytonohjaimet--geforce-rtx-pelaamiseen--rtx-3060'
export const JIMMS_3060_TI = 'https://www.jimms.fi/fi/Product/List/000-1T3/komponentit--naytonohjaimet--geforce-rtx-pelaamiseen--rtx-3060-ti'
export const JIMMS_3070 = 'https://www.jimms.fi/fi/Product/List/000-1SY/komponentit--naytonohjaimet--geforce-rtx-pelaamiseen--rtx-3070'
export const JIMMS_3070_TI ='https://www.jimms.fi/fi/Product/List/000-1U4/komponentit--naytonohjaimet--geforce-rtx-pelaamiseen--rtx-3070-ti'
